### ISSUE TITLE
[Bug] v2.66.1 fails to set up on HA 2026.8 (declared min 2025.7.0): DeviceRegistry.async_get() got an unexpected keyword argument 'include_composite_devices'

### ISSUE THREAD

**Issue by liblit** [iluebbe/maintenance_supporter#144]
### Maintenance Supporter version

v2.66.1

### Home Assistant version

v2.66.1

### Installation method

HACS (default repository)

### What happened

After upgrading to v2.66.1 and restarting, every `maintenance_supporter` config entry fails to set up on HA Core 2026.8.3. All maintenance task entities come up as `restored/unavailable` and never read a live value; install-level "unavailable entity/device" counts jump sharply and stay pinned. The integration is effectively down for the whole installation.

This is a regression on a supported HA version: `hacs.json` declares a 2025.5.7.0-era minimum (`homeassistant: 2025.7.0`) and the v2.66.1 changelog explicitly says "No functional changes on 2026.7/2026.8." v2.66.0 and earlier set up fine on this same core.

### What you expected

v2.66.1 to keep loading on HA 2026.8, as v2.66.0 did, since the release claims no functional changes there. The per-object maintenance entities should report live values instead of sitting `unavailable/restored`.

### Steps to reproduce

1. Run HA Core 2026.8.3 (within the component's declared support) with Maintenance Supporter v2.66.1 (default HACS repo).
2. Restart Home Assistant.
3. Every` maintenance_supporter` config entry fails setup with the `TypeError` below during `async_setup_entry`.
4. Per-object maintenance entities come up `restored/unavailable`.

### Relevant log output

```shell
ERROR (MainThread) [custom_components.maintenance_supporter] Error setting up entry Crumb Muncher for maintenance_supporter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/maintenance_supporter/__init__.py", line 1304, in async_setup_entry
    resolved = resolve_linked_device_id(hass, stored_device_id, own_entry_id=entry.entry_id)
  File "/config/custom_components/maintenance_supporter/helpers/device_link.py", line 67, in resolve_linked_device_id
    live = cast(Any, dev_reg).async_get(device_id, include_composite_devices=False)
TypeError: DeviceRegistry.async_get() got an unexpected keyword argument 'include_composite_devices'
```

### Confirmation

- [x] I searched existing open and closed issues for duplicates.
- [x] I am running a recent HA version (≥ the one in `hacs.json`).

**Comment by iluebbe** [comment]
Thank you for the immediate and precise report — and apologies, this one is squarely on me.

**Root cause:** the 2026.9-readiness change in v2.66.1 keyed its "new registry API" branch on the presence of `DeviceRegistry.async_get_device_by_identifier`. That method already exists on 2026.8, but the `include_composite_devices` keyword the branch then uses only arrives in 2026.9 — so on 2026.8 every config entry died in `async_setup_entry` exactly as in your traceback.

**Why nothing caught it:** the dev container runs 2026.7 and the (deliberately unpinned) CI runs the 2026.9 beta. 2026.8 — the release almost everyone actually runs — was in no test at all. That gap is closed now: CI runs two pytest legs, newest-core-including-betas *and* current stable, and the resolver has regression tests shaped like each core generation.

**Fix:** **v2.66.2** — the probe now checks for the lookup it actually uses. Reproduced your traceback on 2026.8.3 in a throwaway container, then verified the full suite green on 2026.8.3 and 2026.9.0b0. Update via HACS and restart; no configuration changes needed, your entries load as before.
